# Generated by Django 4.1.7 on 2023-03-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_is_published',
            field=models.BooleanField(default=False),
        ),
    ]
