# Generated by Django 4.1.7 on 2023-03-10 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_alter_stock_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 10, 18, 25, 2, 859964)),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='price_with_tax',
            field=models.DecimalField(decimal_places=0, editable=False, max_digits=8, null=True),
        ),
    ]
