# Generated by Django 4.1.7 on 2023-03-11 01:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_cart_last_update_alter_productprice_price_with_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='cart_item_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='cart',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 11, 10, 51, 9, 227333)),
        ),
    ]
