# Generated by Django 4.1.7 on 2023-03-11 02:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_cartitem_cart_item_price_alter_cart_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='is_discount_price_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 11, 11, 11, 15, 904928)),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
