# Generated by Django 4.1.7 on 2023-03-11 02:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0007_productprice_is_discount_price_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 11, 11, 14, 47, 469635)),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart_item_price',
            field=models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=8),
        ),
    ]
