# Generated by Django 4.1.7 on 2023-03-12 05:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0009_rename_purchaseditem_purchaseitem_delete_purchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='C:\\Users\\yusuk\\dev\\projects\\portfolio_site\\static\\images\\commerce\\noimage.jpg', upload_to='product_image/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 12, 14, 2, 17, 390919)),
        ),
    ]
