# Generated by Django 4.1.7 on 2023-03-12 05:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0012_alter_cart_last_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 12, 14, 11, 28, 737420)),
        ),
        migrations.AlterField(
            model_name='stock',
            name='remaining_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
