# Generated by Django 4.1.7 on 2023-03-13 01:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commerce", "0016_remove_product_price_productprice_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_description_short",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cart",
            name="last_update",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 13, 10, 47, 6, 459668)
            ),
        ),
    ]
