# Generated by Django 4.1.7 on 2023-03-13 01:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commerce", "0017_product_product_description_short_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="last_update",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 13, 10, 52, 9, 28636)
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_image",
            field=models.ImageField(
                blank=True,
                default="noimage.jpg",
                null=True,
                upload_to="product_image/%Y/%m/%d/",
            ),
        ),
    ]
