# Generated by Django 4.1.7 on 2023-03-13 03:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commerce", "0018_alter_cart_last_update_alter_product_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="price_with_tax",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="cart",
            name="last_update",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 13, 12, 42, 38, 34127)
            ),
        ),
    ]
