# Generated by Django 4.1.7 on 2023-03-14 04:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commerce", "0021_alter_cart_last_update_alter_purchasehistory_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseitem",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="cart",
            name="last_update",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 14, 13, 2, 35, 372330)
            ),
        ),
    ]
