# Generated by Django 4.1.7 on 2023-03-14 04:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commerce", "0022_purchaseitem_subtotal_alter_cart_last_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="last_update",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 14, 13, 5, 8, 518163)
            ),
        ),
        migrations.AlterField(
            model_name="purchasehistory",
            name="total_price",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="purchaseitem",
            name="purchased_price",
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="purchaseitem",
            name="subtotal",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
        ),
    ]
