# Generated by Django 4.1.7 on 2023-03-09 01:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('card_image', models.ImageField(upload_to='')),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('github_link', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('feature_link', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('is_published', models.BooleanField(default=False)),
                ('tag', models.ManyToManyField(to='pages.tag')),
            ],
        ),
    ]
