# Generated by Django 4.1.7 on 2023-03-09 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_portfolio_github_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='feature_link',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='feature_view_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
