# Generated by Django 4.1.7 on 2023-03-09 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_portfolio_feature_link_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='PortfolioTag',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='tag',
            new_name='portfolio_tag',
        ),
        migrations.RenameField(
            model_name='portfoliotag',
            old_name='tag',
            new_name='portfolio_tag',
        ),
    ]
