# Generated by Django 4.1.7 on 2023-03-08 09:55

from django.db import migrations
import django_editorjs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_blog_posts_blog_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='body',
            field=django_editorjs.fields.EditorJsField(blank=True),
        ),
    ]
