# Generated by Django 4.1.7 on 2023-03-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
